In [6]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from config import api_key
from config import gkey
import gmaps
import os
import json

In [9]:
weather_df = pd.read_csv("cities.csv")
weather_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,date
0,Cherskiy,100,RU,1611861133,85,68.7500,161.3000,-26.90,2.80,2021-01-28 19:12:13
1,Raudeberg,100,NO,1611861133,76,61.9875,5.1352,33.01,21.23,2021-01-28 19:12:13
2,São José da Coroa Grande,22,BR,1611861133,71,-8.8978,-35.1478,81.45,10.33,2021-01-28 19:12:13
3,Mataura,92,NZ,1611860640,81,-46.1927,168.8643,48.00,7.00,2021-01-28 19:04:00
4,Hilo,90,US,1611860710,78,19.7297,-155.0900,69.80,9.22,2021-01-28 19:05:10
...,...,...,...,...,...,...,...,...,...,...
609,Marsh Harbour,49,BS,1611872808,70,26.5412,-77.0636,66.02,26.57,2021-01-28 22:26:48
610,Arauca,4,CO,1611872809,44,7.0847,-70.7591,87.82,5.70,2021-01-28 22:26:49
611,Biri,86,PH,1611872809,81,12.6833,124.3636,78.28,22.48,2021-01-28 22:26:49
612,Mbandaka,100,CD,1611872809,78,0.0487,18.2603,73.54,3.51,2021-01-28 22:26:49
613,Hirara,75,JP,1611872809,58,24.8000,125.2833,57.20,19.57,2021-01-28 22:26:49

In [12]:
gmaps.configure(api_key=gkey)

# Store latitude and longitude in locations
locations = weather_df[["Lat", "Lng"]]

# Store Humidity in humidity
humidity = weather_df["Humidity"]

In [13]:
# Plot Heatmap
fig = gmaps.figure(center=(46.0, -5.0), zoom_level=2)
max_intensity = np.max(humidity)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=100, point_radius=3)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))